
services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant_db
    ports:
      - "6333:6333" # For the main API
      - "6334:6334" # For the gRPC API
    volumes:
      - ./qdrant_data:/qdrant/storage
    restart: unless-stopped

